export { default as CompoundComponent } from './CompoundComponent'
export { default as ControlProps } from './ControlProps'
export { default as Home } from './Home'
export { default as CustomHook } from './CustomHook'
export { default as PropsGetters } from './PropsGetters'
